= Docker Images for compas-ft-riscv

== Prerequisites

In addition to a regular Docker installation, `buildx` is required for building the compas-ft-riscv images.

Dependencies::
[,bash]
----
apt install docker-buildx-plugin
----

== Container/Image Types

=== `compas-ft-riscv-deps`

The `compas-ft-riscv-deps` image is a `debian-stable` images with all the operating system packages required by `compas-ft-riscv` and an unpatched, pre-built, LLVM-project. The LLVM project misses the `compas-ft-riscv` integration.

NOTE: `compas-ft-riscv-deps` is not intended to be used. Use `compas-ft-riscv-dev` or `compas-ft-riscv-base` instead

=== `compas-ft-riscv-base`

The `compas-ft-riscv-base` image contains an installation of LLVM patched and built with `compas-ft-riscv`. Furthermore, the image is pruned of LLVM build artifacts and source-code.

NOTE: `compas-ft-riscv-base` is intended to be used as a "standalone" compiler container.

=== `compas-ft-riscv-dev`

The `compas-ft-riscv-dev` image contains an installation of LLVM patched and built with `compas-ft-riscv`. The image contains the LLVM build artifacts and source-code.

NOTE: `compas-ft-riscv-dev` is intended to be used to inspect the compiler toolchain and possibly extend the `compas-ft-riscv` features.


== Use

=== Pulling prebuilt images

Check our https://hub.docker.com/r/tumeda/[DockerHub] for the latest images and supported OS/LLVM versions:

* https://hub.docker.com/r/tumeda/compas-ft-riscv-base/tags[`compas-ft-riscv-base`]
** debian:stable image:https://img.shields.io/docker/v/tumeda/compas-ft-riscv-base/latest-default-debian-stable["tumeda/compas-ft-riscv-base", link="https://img.shields.io/docker/v/tumeda/compas-ft-riscv-base/latest-default-debian-stable"]

Example commands to pull an image from the registry::
[,bash]
----
docker pull tumeda/compas-ft-riscv-base:latest-default-debian-stable
----

=== Building Images

==== Local

You can build the images locally as follows::
[,bash]
----
cd path/to/compas-ft-riscv/clone
source docker/.env

# Build compas-ft-riscv-deps image
docker buildx build . -f docker/Dockerfile \
                      --tag tumeda/compas-ft-riscv-deps:latest-default-debian-stable \
                      --target compas-ft-riscv-deps-deps \
                      --build-arg BASE_IMAGE=debian:stable \
                      --build-arg workspace_dir=. \
                      --build-arg ENV_LLVM_FROM_SOURCE=${ENV_LLVM_FROM_SOURCE} \
                      --build-arg ENV_LLVM_VERSION=${ENV_LLVM_VERSION} \
                      --build-arg ENV_BUILD_CONFIG=${ENV_BUILD_CONFIG} \
                      --build-arg ENV_BUILD_CXX_STANDARD=${ENV_BUILD_CXX_STANDARD}

# Build compas-ft-riscv-dev image
docker buildx build . -f docker/Dockerfile \
                      --tag tumeda/compas-ft-riscv-deps:latest-default-debian-stable \
                      --target compas-ft-riscv-deps-dev \
                      --build-arg BASE_IMAGE=debian:stable \
                      --build-arg workspace_dir=. \
                      --build-arg ENV_LLVM_FROM_SOURCE=${ENV_LLVM_FROM_SOURCE} \
                      --build-arg ENV_LLVM_VERSION=${ENV_LLVM_VERSION} \
                      --build-arg ENV_BUILD_CONFIG=${ENV_BUILD_CONFIG} \
                      --build-arg ENV_BUILD_CXX_STANDARD=${ENV_BUILD_CXX_STANDARD}

# Build compas-ft-riscv-base image
docker buildx build . -f docker/Dockerfile \
                      --tag tumeda/compas-ft-riscv-deps:latest-default-debian-stable \
                      --target compas-ft-riscv-deps-base \
                      --build-arg BASE_IMAGE=debian:stable \
                      --build-arg workspace_dir=. \
                      --build-arg ENV_LLVM_FROM_SOURCE=${ENV_LLVM_FROM_SOURCE} \
                      --build-arg ENV_LLVM_VERSION=${ENV_LLVM_VERSION} \
                      --build-arg ENV_BUILD_CONFIG=${ENV_BUILD_CONFIG} \
                      --build-arg ENV_BUILD_CXX_STANDARD=${ENV_BUILD_CXX_STANDARD}
----

Build times (excluding pulling of base image) on 18-core workstation::

- `compas-ft-riscv-deps`: `t.b.d.`
- `compas-ft-riscv-dev`: `t.b.d.`
- `compas-ft-riscv-base`: `t.b.d.`

Image sizes::

- `compas-ft-riscv-deps`: `1.66GB`
- `compas-ft-riscv-dev`:
- `compas-ft-riscv-base`:

==== GitHub Action

Manual builds::

Use the `Run Workflow` button on https://github.com/tum-ei-eda/compas-ft-riscv/actions/workflows/container.yml to build images for a specific OS.

CI Setup for DockerHub::

If you want to use the actions on a fork, they will fail due to missing docker credentials. Please export the following variables via `Settings -> Secrets -> Actions` to tell the jobs about your username and password:

- `DOCKER_PASSWORD`
- `DOCKER_USERNAME` (e.g., `tumeda`)
- `DOCKER_REGISTRY` (e.g., `docker.io`, `ghcr.io`)
- `DOCKER_NAMESPACE` (e.g., `tumeda`, `path/to/container`)

=== Running the Images in Docker Containers

To use the previously built or pulled images, run the following commands::

[,bash]
----
# pull a latest image:
docker pull tumeda/compas-ft-riscv-dev:latest-default-debian-stable

# run the pulled container and mount the host's compas-ft-riscv repo:
cd path/to/compas-ft-riscv/clone
docker run -it --rm -v $(pwd):$(pwd) -v .:/compas-ft-riscv tumeda/compas-ft-riscv-dev:latest-default-debian-stable

# in the container:
/llvm-install/bin/llc --version # <-- is the compas-ft-riscv patched llc
----