name: Build LLVM and patch LLVM with COMPAS

on:
  push:
    paths-ignore:
    - doc/
    - README*
    branches:
      - main
    tags:
      - v*
  pull_request:
    paths-ignore:
    - doc/
    - README*
    branches:
      - main
  workflow_dispatch: {}

env:
  BUILD_TYPE: Release

jobs:
  build_llvm_compas:
    strategy:
      matrix:
        os:
          - { name: "ubuntu", version: "latest" }
        llvm:
          #- { src: 'true', tag: '13.0.1' } # <-- the original config
          #- { src: 'true', tag: '14.0.6' } # <-- save CI time
          #- { src: 'true', tag: '15.0.7' } # <-- save CI time
          - { src: 'true', tag: '16.0.6' } # <-- latest (supported) llvm
        llvm_base:
          - { url: "https://github.com/llvm/llvm-project.git", prefix: "llvm-project" }

    runs-on: ${{ matrix.os.name }}-${{ matrix.os.version }}
    container: ${{ matrix.os.name }}:${{ matrix.os.version }}
    name: build_${{ matrix.os.name }}-${{ matrix.os.version }}_compas_llvm${{ matrix.llvm.tag }}

    steps:
    - name: Install git on container
      run: |
        apt update
        apt install -y git
    - name: Clone COMPAS
      uses: actions/checkout@v4
      with:
        path: compas-ft-riscv_src
        submodules: recursive
    - name: Load env vars from docker/.env
      run: |
        while IFS='=' read -r key value || [ -n "$key" ]; do
          [[ -z "$key" || "$key" == \#* ]] && continue
          key="$(echo "$key" | xargs)"
          value="$(echo "$value" | xargs)"
          value="${value%\"}"
          value="${value#\"}"
          echo "$key=$value" >> $GITHUB_ENV
        done < compas-ft-riscv_src/docker/.env
    - name: Requirements (Linux)
      working-directory: ${{runner.workspace}}
      continue-on-error: false
      shell: bash
      run: |
        . ./compas-ft-riscv/compas-ft-riscv_src/docker/setup_debian.sh
        setup_env
    - name: Clone LLVM
      working-directory: ${{runner.workspace}}
      run: |
        . ./compas-ft-riscv/compas-ft-riscv_src/docker/setup_debian.sh
        fetch_llvm "${{runner.workspace}}/llvm_src" \
                   "${{runner.workspace}}/llvm_build" \
                   "/llvm_install" \
                   "${{ env.ENV_LLVM_VERSION }}"
    - name: Patch (LLVM base build)
      working-directory: ${{runner.workspace}}
      run: |
        . ./compas-ft-riscv/compas-ft-riscv_src/docker/setup_debian.sh
        patch_llvm "${{runner.workspace}}/llvm_src" \
                   "${{runner.workspace}}/llvm_build" \
                   "/llvm_install" \
                   "${{ env.ENV_LLVM_VERSION }}" \
                   "${GITHUB_WORKSPACE}/compas-ft-riscv_src/patches/"
        setup_compas "${{runner.workspace}}/compas-ft-riscv/compas-ft-riscv_src" \
                     "${{runner.workspace}}/llvm_src"
    - name: Configure LLVM (base build)
      working-directory: ${{runner.workspace}}
      run: |
        . ./compas-ft-riscv/compas-ft-riscv_src/docker/setup_debian.sh
        configure_llvm "${{runner.workspace}}/llvm_src" \
                   "${{runner.workspace}}/llvm_build" \
                   "/llvm_install" \
                   "${{ env.ENV_LLVM_VERSION }}"
    - name: Compile LLVM with COMPAS
      working-directory: ${{runner.workspace}}
      run: |
        . ./compas-ft-riscv/compas-ft-riscv_src/docker/setup_debian.sh
        build_llvm "${{runner.workspace}}/llvm_src" \
                   "${{runner.workspace}}/llvm_build" \
                   "/llvm_install" \
                   "${{ env.ENV_LLVM_VERSION }}"
    - name: Install LLVM
      working-directory: ${{runner.workspace}}
      run: |
        . ./compas-ft-riscv/compas-ft-riscv_src/docker/setup_debian.sh
        install_llvm "${{runner.workspace}}/llvm_src" \
                   "${{runner.workspace}}/llvm_build" \
                   "/llvm_install" \
                   "${{ env.ENV_LLVM_VERSION }}"
    - name: Upload pre-built LLVM w/ Compas Patch
      uses: actions/upload-artifact@v5
      with:
        name: prebuilt_${{ matrix.os.name }}-${{ matrix.os.version }}_compas_llvm${{ matrix.llvm.tag }}
        path: /llvm_install

  prepare_testenv:
    strategy:
      matrix:
        os:
          - { name: "ubuntu", version: "latest" }
        rvgnu:
          - { url: "https://github.com/xpack-dev-tools/riscv-none-elf-gcc-xpack/releases/download/v13.2.0-2/xpack-riscv-none-elf-gcc-13.2.0-2-linux-x64.tar.gz", prefix: "xpack-riscv-none-elf-gcc-13.2.0-2" }

    runs-on: ${{ matrix.os.name }}-${{ matrix.os.version }}
    container: ${{ matrix.os.name }}:${{ matrix.os.version }}
    name: prepare_testenv_${{ matrix.os.name }}-${{ matrix.os.version }}_rvgnu

    steps:
    - name: Install git on container
      run: |
        apt update
        apt install -y git
    - name: Clone COMPAS
      uses: actions/checkout@v4
      with:
        path: compas-ft-riscv_src
    - name: Requirements (Linux)
      working-directory: ${{runner.workspace}}/compas-ft-riscv/compas-ft-riscv_src
      continue-on-error: false
      shell: bash
      run: |
        . docker/setup_debian.sh
        setup_testenv
    - name: RISCV GNU Tools
      id: cache-rvgnu
      uses: actions/cache@v4
      with:
        path: /rvgnu_install
        key: ${{ matrix.os.name }}-${{ matrix.os.version }}_${{ matrix.rvgnu.prefix }}
        restore-keys: ${{ matrix.os.name }}-${{ matrix.os.version }}_${{ matrix.rvgnu.prefix }}
    - if: ${{ steps.cache-rvgnu.outputs.cache-hit != 'true' }}
      name: Requirements RVGNU
      working-directory: ${{runner.workspace}}/compas-ft-riscv/compas-ft-riscv_src/
      shell: bash
      run: |
        . docker/setup_debian.sh
        fetch_rvgnu "/rvgnu_install" "${{ matrix.rvgnu.url }}" "${{ matrix.rvgnu.prefix }}"
        configure_rvgnu "/rvgnu_install"
        build_rvgnu
        install_rvgnu
        cleanup_rvgnu

  test_compas:
    strategy:
      matrix:
        os:
          - { name: "ubuntu", version: "latest" }
        llvm:
          - { src: 'true', tag: '16.0.6' } # <-- latest (supported) llvm
        rvgnu:
          - { base: "riscv-none-elf"}
        suts:
          - { name: "crc", elf: "crc", funcs: "main,crcSlow,crcFast"}
        isa:
          - { name: "rv64gc"}      
        dmr:
          - { trafo: ""}
          - { trafo: "NZDC" }
          - { trafo: "NZDC+NEMESIS" }
          - { trafo: "NZDC+NEMESEC" }
        cfp:
          - { trafo: "" }
          - { trafo: "CFCSS" }
          - { trafo: "RASM" }
          - { trafo: "RACFED" }

    runs-on: ${{ matrix.os.name }}-${{ matrix.os.version }}
    container: ${{ matrix.os.name }}:${{ matrix.os.version }}
    name: test_compas_${{ matrix.os.name }}-${{ matrix.os.version }}
    needs: [build_llvm_compas, prepare_testenv]
 
    steps:
    - name: Install git on container
      run: |
        apt update
        apt install -y git
    - name: Clone COMPAS
      uses: actions/checkout@v4
      with:
        path: compas-ft-riscv_src
    - name: Requirements (Linux)
      working-directory: ${{runner.workspace}}/compas-ft-riscv/compas-ft-riscv_src
      continue-on-error: false
      shell: bash
      run: |
        . docker/setup_debian.sh
        setup_testenv
    - name: Fetch Compiled LLVM+Compas
      uses: actions/download-artifact@v5
      with:
        name: prebuilt_${{ matrix.os.name }}-${{ matrix.os.version }}_compas_llvm${{ matrix.llvm.tag }} 
        path: /llvm_install
    - name: RISCV GNU Tools
      id: cache-rvgnu
      uses: actions/cache@v4
      with:
        path: /rvgnu_install
        key: ${{ matrix.os.name }}-${{ matrix.os.version }}_${{ matrix.rvgnu.prefix }}
        restore-keys: ${{ matrix.os.name }}-${{ matrix.os.version }}_${{ matrix.rvgnu.prefix }}
    - name: Prepare tools
      shell: bash
      run: |
        chmod -R +x "/rvgnu_install/bin"
        chmod -R +x "/llvm_install/bin"
    - name: Configure Test
      working-directory: ${{runner.workspace}}/compas-ft-riscv/compas-ft-riscv_src
      continue-on-error: false
      shell: bash
      run: |
        cmake -S tests/${{ matrix.suts.name }} -B /${{ matrix.suts.name }}-build -D COMPAS_LLVM_ROOT="/llvm_install" \
              -D RISCV_TOOLCHAIN_BASENAME="${{ matrix.rvgnu.base}}" -D RISCV_TOOLCHAIN_PREFIX="/rvgnu_install" \
              -D RISCV_ISA="${{ matrix.isa.name }}" \
              -D DMR_MOD="${{ matrix.dmr.trafo }}" -D DMR_FUNCTIONS="${{ matrix.suts.funcs }}" \
              -D CFP_MOD="${{ matrix.cfp.trafo }}" -D CFP_FUNCTIONS="${{ matrix.suts.funcs }}"
    - name: Compile Test
      working-directory: ${{runner.workspace}}/compas-ft-riscv/compas-ft-riscv_src
      continue-on-error: false
      shell: bash
      run: |
        cmake --build /${{ matrix.suts.name }}-build
    - name: Run Test
      working-directory: ${{runner.workspace}}/compas-ft-riscv/compas-ft-riscv_src
      continue-on-error: false
      shell: bash
      run: |
        /rvgnu_install/bin/spike /rvgnu_install/${{ matrix.rvgnu.base}}/bin/ok ${{ matrix.suts.name }}-build/${{ matrix.suts.name }}



